/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as FixosRouteImport } from './routes/fixos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as TransacoesRouteImport } from './routes/transacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const FixosRoute = FixosRouteImport.update({
  id: '/fixos',
  path: '/fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/fixos': typeof FixosRoute
  '/metas': typeof MetasRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/fixos': typeof FixosRoute
  '/metas': typeof MetasRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/fixos': typeof FixosRoute
  '/metas': typeof MetasRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contas' | '/fixos' | '/metas' | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contas' | '/fixos' | '/metas' | '/transacoes'
  id: '__root__' | '/' | '/contas' | '/fixos' | '/metas' | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContasRoute: typeof ContasRoute
  FixosRoute: typeof FixosRoute
  MetasRoute: typeof MetasRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixos': {
      id: '/fixos'
      path: '/fixos'
      fullPath: '/fixos'
      preLoaderRoute: typeof FixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContasRoute: ContasRoute,
  FixosRoute: FixosRoute,
  MetasRoute: MetasRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
